### ISSUE TITLE
timeRangeViewType: TimeRangeViewType.end does not select the end time range view first

### ISSUE THREAD

**Issue by jxtzzz** [trashfeed/simple_time_range_picker#7]
I have a row with two TextFormFields that open (on tap) a TimeRangePicker, however I would like that when I tap the first one, the picker opens with the startTime view and vice versa on the second one.

I have used the timeRangeViewType: TimeRangeViewType.end on the picker in question but it still opens with the start time view.

![image](https://user-images.githubusercontent.com/51048697/137962796-3cfd8033-48e4-4963-8e33-61a158787d45.png)
![image](https://user-images.githubusercontent.com/51048697/137962868-bdd1ebb2-9264-4fa3-928f-6f0bdd792164.png)

**Comment by trashfeed** [comment]
@jxtzzz 
Nice! I fixed it, please wait for the next release. Thanks for the report 🙏
